apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd
  annotations:
spec:
  rules:
    - host: hello-argo.veeramagicworld.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ template "helm-guestbook.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
